### ISSUE TITLE
Add block comments to important functions to describe parameters

### ISSUE THREAD

**Issue by adamgayoso** [JonathanShor/Doublet-Detection#14]
see create simple synthetic for an example (once I merge)

**Comment by JonathanShor** [comment]
See [https://github.com/JonathanShor/Doublet-Detection/tree/docstring-stubs](url)

**Comment by JonathanShor** [comment]
Need another round of this.

**Comment by adamgayoso** [comment]
This will be taken care of in the class restructure.
