### ISSUE TITLE
Generating doublets for detection: Prohibit same cell types?

### ISSUE THREAD

**Issue by JonathanShor** [JonathanShor/Doublet-Detection#20]
While a doublet with two of the same cell type in one droplet is technically a doublet (let's call it a duplicate doublet), should we prohibit producing simulated doublets like this when calling synthetic.sampleCellRead to identify the doublet clusters?

Maybe do some testing to see where these tend to fall with respect to non-duplicate doublets: are they falling within "normal" clusters? Or are they just as informative as the non-duplicate doublets, falling within doublet clusters?

Perhaps this suggests a new visualization to produce: pick 3 cell types, assign primary color to each, produce doublets of those 3 cell types, assign corresponding secondary colors to each doublet type, chart and see how they fall out relative to each other. Are duplicate doublets distinct from their parent cluster?

**Comment by adamgayoso** [comment]
I would like to think doublets of the same type are picking up real
dpublets of the same type. Since that type of doublet would be closest.

**Comment by adamgayoso** [comment]
My guess is that clusters with over 80-90 percent score are these clusters.

**Comment by JonathanShor** [comment]
> I would like to think doublets of the same type are picking up real
> dpublets of the same type. Since that type of doublet would be closest.

I agree, but I don't know it.
Pending a design decision to actually make use of this, #25 implements an option for this.

**Comment by adamgayoso** [comment]
Closing this. Same cell types cluster with parent cluster.
